### ISSUE TITLE
Using colon in time format yield to miniscule font

### ISSUE THREAD

**Issue by kuon** [muesli/deckmaster#141]
If I use a colon as time separator, it yield to a minuscule font (see photo).

```toml
[[keys]]
  index = 0
  [keys.widget]
    id = "button"
    [keys.widget.config]
      label = "Music"
  [keys.action]
    deck = "music.deck"

[[keys]]
  index = 3
  [keys.widget]
    id = "time"
    [keys.widget.config]
      format = "%H:%i;%s"
      color = "#fefefe" # optional
      fontsize = 1.0 # optional

```

![image](https://github.com/muesli/deckmaster/assets/160200/68724294-29bc-4d5a-b76a-0850ea6a597d)
