### ISSUE TITLE
A way to debug `exec`?

### ISSUE THREAD

**Issue by nahsi** [muesli/deckmaster#64]
I'm trying to trigger a webhook with httpie (curl alternative) like this:
```toml
[[keys]]
  index = 13
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "./assets/Nightlife/misc/Screenshot.png"
  [keys.action]
    exec = "https POST home-assistant.service.consul/api/webhook/media"
```

It works when I run it myself and doesn't when it is triggered by deckmaster.

I'm not sure how to debug it since there is no log. I've tried to execute a script inside of which I've redirected command stdout and stdin to a file, but the file is not created. However if I add `exit 1` to the end of the script I will get `command failed: exit status 1` meaning it *did* run the script.

I guess this is something to do with how golang exec module works?
